name: Github 2 Dockerhub 2 Slack
on:
  push:
    branches:
    - "release"

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    
    steps:

    # https://github.com/marketplace/actions/checkout
    - name: Checkout the source
      uses: actions/checkout@v3
    
    - name: Get docker build
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    
    - name: Login to hub.docker.io
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push to hub.docker.io
      uses: docker/build-push-action@v2
      with:
        # relative path to the place where source code with Dockerfile is located
        context: .
        # Note: tags has to be all lower-case
        tags: |
          somik123/randimg:1.0.2
    
  #  - name: Post message on slack
  #    uses: bluenovaio/action-slack@main 
  #    with:
  #      username: "ExampleBot"
  #      icon_emoji: ":robot_face:"
  #      text: "This is a test message"
  #      webhook_url: ${{ secrets.SLACK_WEBHOOK }} 